# Generated by Django 4.2.4 on 2023-09-01 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandleData',
        ),
        migrations.DeleteModel(
            name='CandleHourData',
        ),
        migrations.DeleteModel(
            name='VolumeData',
        ),
        migrations.AlterModelOptions(
            name='usernotifydata',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='usernotifydata',
            name='status',
        ),
        migrations.AddField(
            model_name='usernotifydata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
