# Generated by Django 4.2.4 on 2023-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usernotifydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='limitcount',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tlgactive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(),
        ),
    ]
