# Generated by Django 4.2.4 on 2023-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_candledata_delete_candlehourdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
