# Generated by Django 4.2.4 on 2023-09-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telephone',
            new_name='phone',
        ),
    ]
