# Generated by Django 4.2.4 on 2023-09-03 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_telephone_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 0)),
        ),
    ]
