# Generated by Django 4.2.4 on 2023-09-03 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customuser_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 23, 59, 59)),
        ),
    ]
