# Generated by Django 4.2.4 on 2023-09-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
