# Generated by Django 4.2.4 on 2023-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customuser_limitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_login',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tlgactive',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
