# Generated by Django 4.2.4 on 2023-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customuser_is_login_alter_customuser_tlgactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='limitcount',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=5),
        ),
    ]
