# Generated by Django 4.2.4 on 2023-09-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_customuser_limitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPriceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=10, default=500, max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
