# Generated by Django 4.2.4 on 2023-09-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coinpricedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpricedata',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coinpricedata',
            name='symbol',
        ),
        migrations.AddField(
            model_name='coinpricedata',
            name='data',
            field=models.TextField(default='[]'),
        ),
    ]
