# Generated by Django 4.2.4 on 2023-09-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_coinpricedata_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinPriceData',
        ),
    ]
