# Generated by Django 4.2.4 on 2023-09-25 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_coinpricedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvancedSettingsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['userid'],
            },
        ),
    ]
