# Generated by Django 4.2.4 on 2023-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_useradvancedsettingsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradvancedsettingsdata',
            name='istlg',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
