# Generated by Django 4.2.4 on 2023-10-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_useradvancedsettingsdata_istlg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coindata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useradvancedsettingsdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usernotifydata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usersettingsdata',
            options={},
        ),
    ]
